export const runtime = "nodejs";

import { NextRequest, NextResponse } from "next/server";
import connectToDatabase from "@/database/dbConnect";
import Booking from "@/models/Booking";
import { requireAuth } from "@/lib/authGuard";
import QRCode from "qrcode";
import { uploadReceiptToS3 } from "@/lib/uploadToS3";

async function renderReceiptHtml(booking: any, qrCodeUrl: string) {
  const client = booking.clientId || {};
  const barber = booking.barberId || {};

  const formattedAmount = new Intl.NumberFormat("en-NG", {
    style: "currency",
    currency: "NGN",
    maximumFractionDigits: 0,
  }).format(booking.amountPaid ?? booking.estimatedPrice ?? 0);

  return `
  <!doctype html>
  <html>
  <head>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
      body { font-family: Inter, sans-serif; }
      .page { width: 850px; margin: auto; padding: 36px; background: white; }
    </style>
  </head>

  <body class="bg-gray-100">
    <div class="page rounded-xl shadow-xl">

      <!-- HEADER -->
      <div class="flex items-center justify-between pb-4 border-b">
        <div>
          <h1 class="text-3xl font-bold text-orange-500">BarbDegree</h1>
          <p class="text-gray-500 text-sm">Premium Grooming • Smart Booking</p>
        </div>

        <img src="https://upload.wikimedia.org/wikipedia/commons/3/38/Question_mark_white_icon.svg"
             alt="logo"
             width="60"
             height="60"
             class="opacity-70" />
      </div>

      <!-- MAIN INFO -->
      <div class="mt-6 grid grid-cols-2 gap-6">
        <div>
          <h3 class="font-bold text-gray-700">Client Information</h3>
          <p>${client.name}</p>
          <p class="text-sm text-gray-500">${client.email}</p>
        </div>

        <div>
          <h3 class="font-bold text-gray-700">Barber Details</h3>
          <p>${barber.name}</p>
          <p class="text-sm text-gray-500">${barber.location ?? ""}</p>
        </div>
      </div>

      <!-- SERVICE BOX -->
      <div class="mt-8 p-5 rounded-lg bg-gray-100">
        <p class="text-sm text-gray-500">Service</p>
        <p class="text-lg font-semibold">${booking.service}</p>

        <p class="text-sm mt-3 text-gray-500">Amount Paid</p>
        <p class="text-3xl font-bold">${formattedAmount}</p>
      </div>

      <!-- PAYMENT META -->
      <div class="mt-6">
        <p class="text-sm text-gray-500">Payment Reference</p>
        <p>${booking.paymentReference}</p>

        <p class="text-sm text-gray-500 mt-3">Status</p>
        <p class="font-semibold">${booking.paymentStatus}</p>
      </div>

      <!-- QR CODE -->
      <div class="mt-10 text-center">
        <img src="${qrCodeUrl}" width="140" class="mx-auto" />
        <p class="text-sm text-gray-400 mt-2">Scan to verify receipt</p>
      </div>

      <footer class="mt-10 text-center text-gray-500 text-xs">
        Receipt generated by BarbDegree • ${new Date().getFullYear()}
      </footer>

    </div>
  </body>
  </html>
  `;
}

export async function GET(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const { user, unauthorized } = await requireAuth(req);
    if (unauthorized) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    await connectToDatabase();

    const booking = await Booking.findById(params.id)
      .populate("clientId")
      .populate("barberId")
      .lean();

    if (!booking) return NextResponse.json({ error: "Booking not found" }, { status: 404 });

    // OWNER + ADMIN ONLY
    if (
      booking.clientId._id.toString() !== user.id &&
      user.role !== "admin"
    ) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const puppeteer = (await import("puppeteer")).default;

    // QR Code points to receipt verify page
    const qrCodeUrl = await QRCode.toDataURL(
      `${process.env.NEXT_PUBLIC_APP_URL}/receipt/verify/${booking._id}`
    );

    const browser = await puppeteer.launch({ headless: "new" });
    const page = await browser.newPage();

    const html = await renderReceiptHtml(booking, qrCodeUrl);
    await page.setContent(html, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
    });

    await browser.close();

    // Upload to S3
    const s3Url = await uploadReceiptToS3(pdfBuffer, `receipt_${booking._id}.pdf`);

    // Save URL to database
    await Booking.findByIdAndUpdate(params.id, {
      receiptUrl: s3Url,
    });

    return NextResponse.json({
      success: true,
      message: "Receipt generated successfully",
      pdfUrl: s3Url,
    });

  } catch (err) {
    console.log("Receipt error:", err);
    return NextResponse.json(
      { error: "Failed to generate receipt" },
      { status: 500 }
    );
  }
}
