import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import localFont from "next/font/local";
import Script from "next/script";
import Providers from "@/components/Providers";
import { authOptions } from "@/lib/authOptions";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const browserExtensionAttributeCleanup = `
(() => {
  const attributes = ["bis_skin_checked"];
  const selector = attributes.map((attribute) => "[" + attribute + "]").join(",");

  const clean = (node) => {
    if (!node || node.nodeType !== 1) return;

    for (const attribute of attributes) {
      if (node.hasAttribute(attribute)) {
        node.removeAttribute(attribute);
      }
    }

    if (node.querySelectorAll) {
      node.querySelectorAll(selector).forEach((element) => {
        for (const attribute of attributes) {
          element.removeAttribute(attribute);
        }
      });
    }
  };

  clean(document.documentElement);

  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type === "attributes") {
        clean(mutation.target);
      }

      mutation.addedNodes.forEach(clean);
    }
  });

  observer.observe(document.documentElement, {
    attributeFilter: attributes,
    attributes: true,
    childList: true,
    subtree: true,
  });

  window.addEventListener("load", () => {
    window.setTimeout(() => observer.disconnect(), 1000);
  }, { once: true });
})();
`;

const manrope = localFont({
  src: "../../public/fonts/Manrope-Variable.ttf",
  variable: "--font-manrope",
  display: "swap",
  weight: "200 800",
});

const syncopate = localFont({
  src: [
    {
      path: "../../public/fonts/Syncopate-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Syncopate-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-syncopate",
  display: "swap",
});


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    // show html
    <html lang="en" suppressHydrationWarning>
      {/* show body */}
      <body
        className={`${manrope.variable} ${syncopate.variable} antialiased`}
        suppressHydrationWarning
      >
        {process.env.NODE_ENV === "development" ? (
          <Script
            id="browser-extension-attribute-cleanup"
            strategy="beforeInteractive"
            dangerouslySetInnerHTML={{
              __html: browserExtensionAttributeCleanup,
            }}
          />
        ) : null}
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
