/**
 * AUTO-FILE-COMMENT: src/app/layout.tsx
 * Purpose: Explains the role of this module and documents its functions.
 * Notes: Comments are documentation-only and do not change runtime behavior.
 */
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import Script from "next/script";
import Providers from "@/components/Providers";
import { authOptions } from "@/lib/authOptions";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const browserExtensionAttributeCleanup = `
(() => {
  const attributes = ["bis_skin_checked"];
  const selector = attributes.map((attribute) => "[" + attribute + "]").join(",");

  const clean = (node) => {
    if (!node || node.nodeType !== 1) return;

    for (const attribute of attributes) {
      if (node.hasAttribute(attribute)) {
        node.removeAttribute(attribute);
      }
    }

    if (node.querySelectorAll) {
      node.querySelectorAll(selector).forEach((element) => {
        for (const attribute of attributes) {
          element.removeAttribute(attribute);
        }
      });
    }
  };

  clean(document.documentElement);

  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type === "attributes") {
        clean(mutation.target);
      }

      mutation.addedNodes.forEach(clean);
    }
  });

  observer.observe(document.documentElement, {
    attributeFilter: attributes,
    attributes: true,
    childList: true,
    subtree: true,
  });

  window.addEventListener("load", () => {
    window.setTimeout(() => observer.disconnect(), 1000);
  }, { once: true });
})();
`;

/**
 * AUTO-FUNCTION-COMMENT: RootLayout
 * Purpose: Handles root layout.
 * Line-by-line:
 * 1. Executes `return (`.
 * 2. Executes `<html lang="en" suppressHydrationWarning>`.
 * 3. Executes `<body`.
 * 4. Executes `className={\`${geistSans.variable} ${geistMono.variable} antialiased\`}`.
 * 5. Executes `>`.
 * 6. Executes `<Providers>{children}</Providers>`.
 * 7. Executes `</body>`.
 * 8. Executes `</html>`.
 * 9. Executes `);`.
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {process.env.NODE_ENV === "development" ? (
          <Script
            id="browser-extension-attribute-cleanup"
            strategy="beforeInteractive"
            dangerouslySetInnerHTML={{
              __html: browserExtensionAttributeCleanup,
            }}
          />
        ) : null}
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
