import type { Metadata } from "next";
import Providers from "@/components/Providers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * AUTO-FUNCTION-COMMENT: RootLayout
 * Purpose: Handles root layout.
 * Line-by-line:
 * 1. Executes `return (`.
 * 2. Executes `<html lang="en" suppressHydrationWarning>`.
 * 3. Executes `<body`.
 * 4. Executes `className={\`${geistSans.variable} ${geistMono.variable} antialiased\`}`.
 * 5. Executes `>`.
 * 6. Executes `<Providers>{children}</Providers>`.
 * 7. Executes `</body>`.
 * 8. Executes `</html>`.
 * 9. Executes `);`.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
